app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('backstage/', admin.site.urls),
    path('host/', include('host.urls')),
    path('', include('triviagame.urls')),
]

game/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('uncurse/', views.uncurse, name='uncurse'),
    path('join/', views.join_game, name='join_game'),
    path('join/<int:id>/<str:code>/', views.join_game, name='join_game'),
    path('join/team/', views.create_team, name='create_team'),
    path('rejoin/', views.rejoin_team, name='rejoin_team'),
    path('rejoin/<int:id>/<str:code>/', views.rejoin_team, name='rejoin_team'),
    path('play/', views.play, name='play'),
    path('play/p', views.page_list_hx, name='page_list_hx'),
    path('play/s', views.play_poll_hx, name='play_poll_hx'),
    path('play/<int:page_order>/', views.answer_sheet, name='answer_sheet'),
    path('play/q/<int:question_id>/', views.question_hx, name='question_hx'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('healthcheck/', views.healthcheck, name='healthcheck'),
]

host/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.host_home, name='host_home'),
    path('<int:game_id>/toggle/<int:new_state>', views.update_game_state, name='update_game_state'),
    path('<int:game_id>/pages/', views.pages, name='pages'),
    path('<int:game_id>/pages/state/', views.set_page_state, name='set_page_state'),
    path('<int:game_id>/pages/<int:page_id>', views.score_page, name='score_page'),
    path('<int:game_id>/score/', views.assign_score, name='assign_score'),
    path('<int:game_id>/game.json', views.game_data, name='game_data'),
    path('<int:game_id>/leaderboard.json', views.host_leaderboard_stats, name='host_leaderboard_stats'),
    path('<int:game_id>/leaderboard', views.host_leaderboard, name='host_leaderboard'),
    path('<int:game_id>/team/<int:team_id>', views.team_page, name='team_page'),
    path('<int:game_id>/team/<int:team_id>/edit', views.hx_edit_team, name='edit_team'),
    path('editor/new/', views.new_game, name='new_game'),
    path('editor/<int:game_id>/', views.edit_game, name='edit_game'),
    path('editor/<int:game_id>/audit', views.audit_game, name='audit_game'),
    path('editor/<int:game_id>/hosts', views.edit_game_hosts, name='edit_game_hosts'),
    path('editor/<int:game_id>/hosts/<int:user_id>', views.hx_remove_game_host, name='remove_game_host'),
    path('editor/page/<int:page_id>/', views.edit_page, name='edit_page'),
    path('editor/page/<int:page_id>/metadata/', views.hx_edit_page_metadata, name='edit_page_metadata'),
    path('editor/page/<int:page_id>/up/', views.page_move, { 'delta': -1 }, name='page_up'),
    path('editor/page/<int:page_id>/down/', views.page_move, { 'delta': 1 }, name='page_down'),
    path('editor/page/new/<int:game_id>/', views.new_page, name='new_page'),
    path('editor/page/<int:page_id>/delete/', views.delete_page, name='delete_page'),
    path('editor/question/<int:question_id>/', views.edit_question, name='edit_question'),
    path('editor/question/<int:question_id>/up/', views.question_move, { 'delta': -1 }, name='question_up'),
    path('editor/question/<int:question_id>/down/', views.question_move, { 'delta': 1 }, name='question_down'),
    path('editor/question/new/<int:page_id>/', views.new_question, name='new_question'),
    path('editor/question/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('auth/prelogout', views.host_confirm_logout, name='confirm_logout'),
    path('auth/', include('django.contrib.auth.urls')),
]

triviagame/urls.py
from django.contrib import admin
from django.urls import path, include

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('backstage/', admin.site.urls),
    path('host/', include('host.urls')),
    path('', include('game.urls')),
] + debug_toolbar_urls()

app/host/models.py
from django.contrib.auth import get_user_model
from django.db import models

from triviagame.models import Game


class GameHostPermissions(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    can_view = models.BooleanField()
    can_host = models.BooleanField()
    can_edit = models.BooleanField()

    def __str__(self):
        perm_bits = "".join([
            "E" if self.can_edit else "-",
            "H" if self.can_host else "-",
            "V" if self.can_view else "-",
        ])
        return f"{self.user}@{self.game}: {perm_bits}"

game/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.crypto import get_random_string


def generate_passcode():
    return get_random_string(10, 'ABCDEFGHJKLMNPQRTUVWXYZ2346789')


class Game(models.Model):
    class GameState(models.IntegerChoices):
        CLOSED = 0          # game can't be accessed
        ACCEPTING_TEAMS = 1 # game is open, new teams can register
        NO_NEW_TEAMS = 2    # game is open, only existing teams can access

    name = models.CharField(max_length=60)
    passcode = models.CharField(max_length=20, default=generate_passcode)
    state = models.IntegerField(
        choices=GameState.choices,
        default=GameState.CLOSED,
    )
    last_edit_time = models.DateTimeField(
        auto_now=True,
        blank=True,
        editable=False,
    )

    class Meta:
        ordering = ['-last_edit_time']
        permissions = [
            ('host_game', 'Host game'),
        ]

    def __str__(self):
        return self.name
    
    @property
    def is_closed(self):
        return self.state == Game.GameState.CLOSED
    
    @property
    def is_accepting_teams(self):
        return self.state == Game.GameState.ACCEPTING_TEAMS

    @property
    def is_open_but_not_accepting_teams(self):
        return self.state == Game.GameState.NO_NEW_TEAMS

    @property
    def is_open(self):
        "Any kind of open, whether accepting new teams or not"
        return self.state != Game.GameState.CLOSED


class Team(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    members = models.CharField(max_length=200, blank=True)
    passcode = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['game', 'name']
        constraints = [
            models.UniqueConstraint(
                fields=['game', 'name'],
                name='ensure_unique_team_names',
            ),
        ]


class Page(models.Model):
    MYSTERIES = [
        'The mysterious future...',
        'All will be revealed in time.',
        'Wouldn\'t you like to know?',
        'The suspense must be killing you!',
        'It\'s a secret to everybody.',
    ]

    class PageState(models.IntegerChoices):
        LOCKED = 0      # players cannot open the page at all
        OPEN = 1        # players can open and answer the page
        SCORING = 2     # players can open, but not answer, the page

    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    order = models.SmallIntegerField()
    state = models.IntegerField(
        choices=PageState.choices,
        default=PageState.LOCKED,
    )
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    is_hidden = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.game} :: {self.order}. {self.title}"
    
    class Meta:
        ordering = ['game', 'order']
        constraints = [
            models.UniqueConstraint(
                fields=['game', 'order'],
                name='ensure_page_order',
            ),
        ]
    
    def mystery_description(self):
        index = self.game.id + self.order
        return Page.MYSTERIES[index % len(Page.MYSTERIES)]

    # these properties are convenient in templates    
    @property
    def total_points(self):
        return (
            self.question_set
            .aggregate(points=models.Sum('possible_points'))
        ).get('points', None) or 0

    @property
    def is_locked(self):
        return self.state == Page.PageState.LOCKED
    
    @property
    def is_open(self):
        return self.state == Page.PageState.OPEN
    
    @property
    def is_scoring(self):
        return self.state == Page.PageState.SCORING
    
    @property
    def bootstrap_locked_button_styles(self):
        match self.state:
            case Page.PageState.LOCKED:
                return 'btn-outline-secondary disabled'
            case Page.PageState.OPEN:
                return 'btn-outline-primary'
            case Page.PageState.SCORING:
                return 'btn-outline-primary'
        return ''
    
    @property
    def bootstrap_open_button_styles(self):
        match self.state:
            case Page.PageState.LOCKED:
                return 'btn-primary'
            case Page.PageState.OPEN:
                return 'btn-outline-secondary disabled'
            case Page.PageState.SCORING:
                return 'btn-outline-primary'
        return ''
    
    @property
    def bootstrap_scoring_button_styles(self):
        match self.state:
            case Page.PageState.LOCKED:
                return 'btn-outline-primary'
            case Page.PageState.OPEN:
                return 'btn-primary'
            case Page.PageState.SCORING:
                return 'btn-outline-secondary disabled'
        return ''
    # end template properties


class Question(models.Model):
    page = models.ForeignKey(Page, on_delete=models.PROTECT)
    order = models.SmallIntegerField()
    question = models.TextField()
    answer = models.TextField(blank=True)
    possible_points = models.SmallIntegerField(
        default=1,
        validators=[MinValueValidator(limit_value=1)],
    )

    def __str__(self):
        return f"{self.order}. {self.question}"

    class Meta:
        ordering = ['page', 'order']
        constraints = [
            models.UniqueConstraint(
                fields=['page', 'order'],
                name='ensure_question_order',
            ),
        ]
    
    def points_range(self):
        return range(0, self.possible_points + 1)


class Response(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    value = models.CharField(max_length=100)
    graded = models.BooleanField(default=False)
    score = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.value

    class Meta:
        ordering = ['question', 'team']
        constraints = [
            models.UniqueConstraint(
                fields=['question', 'team'],
                name='one_answer_per_team',
            ),
        ]

host/models.py
from django.db import models

app/host/forms.py
from django import forms
from triviagame.models import Game, Page, Question
from triviagame.widgets import Bs5TextInput, Bs5Textarea



class SomePageForm(forms.Form):
    page = forms.IntegerField(widget=forms.HiddenInput)


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'name',
        ]
        widgets = {
            'name': Bs5TextInput,
        }
        labels = {
            'name': 'Game name',
        }


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = [
            'title',
            'description',
        ]
        widgets = {
            'title': Bs5TextInput,
            'description': Bs5Textarea,
        }
        labels = {
            'title': 'Page title',
            'description': 'Long description',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'question',
            'answer',
        ]
        widgets = {
            'question': Bs5Textarea,
            'answer': Bs5Textarea,
        }

host/forms.py
from django import forms
from django.contrib.auth import get_user_model

from game.models import Game, Page, Question, Team
from game.widgets import (
    Bs5TextInput,
    Bs5NumberInput,
    Bs5Textarea,
    Bs5Select,
)


User = get_user_model()


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'name',
        ]
        widgets = {
            'name': Bs5TextInput(attrs={
                'data-1p-ignore': True,
                'autocomplete': 'off',
            }),
        }
        labels = {
            'name': 'Game name',
        }


class GameHostForm(forms.Form):
    host = forms.ModelChoiceField(
        None,
        required=True,
        label="Add additional host",
        widget=Bs5Select,
    )

    def __init__(self, data=None, queryset=None, *args, **kwargs):
        super().__init__(data, *args, **kwargs)
        self.fields['host'].queryset = queryset


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = [
            'title',
            'description',
            'is_hidden',
        ]
        widgets = {
            'title': Bs5TextInput(attrs={
                'autocomplete': 'off',
            }),
            'description': Bs5Textarea,
        }
        labels = {
            'title': 'Page title',
            'description': 'Long description (Markdown allowed)',
            'is_hidden': 'Hide this page while it\'s not open?',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'question',
            'answer',
            'possible_points',
        ]
        widgets = {
            'question': Bs5Textarea,
            'answer': Bs5Textarea,
            'possible_points': Bs5NumberInput,
        }
        labels = {
            'question': 'Question (Markdown allowed)',
            'answer': 'Answer (Markdown allowed)',
        }


class TeamForm(forms.Form):
    name = forms.CharField(
        label='Team name',
        max_length=200,
        widget=Bs5TextInput(attrs={
            'autocomplete': 'off',
            'data-1p-ignore': True,
        }),
    )
    members = forms.CharField(
        label='Team members (display only, no required format)',
        max_length=200,
        required=False,
        widget=Bs5TextInput(attrs={
            'autocomplete': 'off',
        }),
    )

host/templates/host/_games_list.html
{% load guardian_tags %}
{% for game in games %}
<p>
  {% get_obj_perms user for game as "perms" %}
  <a href="{% url 'pages' game.id %}">{{ game }}</a>
  {% if "change_game" in perms %}{% if game.is_open %} (<span class="text-secondary">can't edit while open</span>){% else %} (<a href="{% url 'edit_game' game.id %}">edit</a>){% endif %}{% endif %}
</p>
{% endfor %}

host/templates/host/_pages_list.html
{% load guardian_tags %}
{% get_obj_perms user for game as "perms" %}
{% for page in game.page_set.all %}
<div class="card mb-3{% if page.is_open and game.is_open %} border-success{% elif page.is_open %} border-warning{% endif %}">
  <div class="card-header{% if page.is_open and game.is_open %} text-white bg-success{% elif page.is_open %} text-white bg-warning{% endif %}">{{ page.order }}. {{ page.title }} <span class="badge bg-secondary">{{ page.question_set.count }} question{{ page.question_set.count|pluralize }}</span>{% if page.is_hidden %}{% if page.is_locked %} <span class="badge bg-primary">hidden page</span>{% else %} <span class="badge bg-secondary">revealed page</span>{% endif %}{% endif %} <span class="badge bg-info">{{ page.total_points }} point{{ page.total_points|pluralize }}</span></div>
  <div class="card-body">
    <div class="card-title markdown-needed">{{ page.description }}</div>
    <div class="card-text">
      {% if 'host_game' in perms %}
      <a class="btn {{ page.bootstrap_locked_button_styles }}"
        hx-post="{% url 'set_page_state' game.id %}"
        hx-vals='{"page":{{ page.id }},"state":"LOCKED"}'>
      {% else %}
      <a class="btn btn-outline-secondary disabled">
      {% endif %}
        Lock this page 🔒
      </a>
      {% if 'host_game' in perms %}
      <a class="btn {{ page.bootstrap_open_button_styles }}"
        hx-post="{% url 'set_page_state' game.id %}"
        hx-vals='{"page":{{ page.id }},"state":"OPEN"}'>
      {% else %}
      <a class="btn btn-outline-secondary disabled">
      {% endif %}
        Open this page ✏️
      </a>
      {% if 'host_game' in perms %}
      <a class="btn {{ page.bootstrap_scoring_button_styles }}"
        hx-post="{% url 'set_page_state' game.id %}"
        hx-vals='{"page":{{ page.id }},"state":"SCORING"}'>
      {% else %}
      <a class="btn btn-outline-secondary disabled">
      {% endif %}
        Stop accepting answers ✋
      </a>
    </div>
    <div class="card-text mt-2">
      <a href="{% url 'score_page' game.id page.id %}" class="btn btn-{% if page.state != 2 %}outline-{% endif %}primary mb-2">
        {% if page.is_scoring %}Score this page ✅{% else %}Review this page 🧐{% endif %}
      </a>
    </div>
  </div>
</div>
{% empty %}
<p>No pages found.</p>
{% endfor %}

host/templates/host/_question_review.html
<div class="card mb-3" id="question-card-{{ question.id }}">
  <div class="card-header">
    Question {{ question.order }} <span class="badge bg-info">{{ question.possible_points }} point{{ question.possible_points|pluralize }}</span>
  </div>
  <div class="card-body">
    <p class="card-text markdown-needed">{{ question.question }}</p>
    <div class="hstack gap-2 mb-3 p-1 border rounded-start bg-success-subtle">
      <div>Correct answer</div>
      <div class="vr"></div>
      <div class="markdown-needed">{{ question.answer }}</div>
    </div>
    <table class="table table-sm">
    <thead>
      <tr>
        <td>Response</td>
        <td>Team</td>
      </tr>
    </thead>
    {% for response in question.response_set.all %}
    <tr>
      </td>
      <td>{{ response.value }}</td>
      <td><abbr title="{{ response.team.members }}">{{ response.team.name }}</abbr></td>
    </tr>
    {% endfor %}
    </table>
  </div>
</div>

host/templates/host/_question_score.html
{# this template must only depend on `question` and `game` because it #}
{# is invoked in the HTMX view `assign_score` in addition to being #}
{# included in scoring.html #}
<div class="card mb-3" id="question-card-{{ question.id }}">
  <div class="card-header">
    Question {{ question.order }} <span class="badge bg-info">{{ question.possible_points }} point{{ question.possible_points|pluralize }}</span>
  </div>
  <div class="card-body">
    <p class="card-text markdown-needed">{{ question.question }}</p>
    <div class="hstack gap-2 mb-3 p-1 border rounded-start bg-success-subtle">
      <div>Correct answer</div>
      <div class="vr"></div>
      <div class="markdown-needed">{{ question.answer }}</div>
    </div>
    <table class="table table-sm">
    <thead>
      <tr>
        <td>Points</td>
        <td>Response</td>
        <td>Team</td>
      </tr>
    </thead>
    {% for response in question.response_set.all %}
    <tr{% if not response.graded %} class="table-warning"{% endif %}>
      <td>
        <div class="btn-group" role="group">
          <button class="btn btn-sm btn-outline-secondary"
            {% if not response.graded %}disabled{% endif %}
            hx-post="{% url 'assign_score' game.id %}"
            hx-vals='{"response":{{ response.id }},"score":-1 }'
            hx-target="#question-card-{{ response.question.id }}"
            hx-swap="outerHTML"
            hx-confirm="This will un-score this team's response, are you sure?">🚫</button>
          {% for points in question.points_range %}
          <button
            {% if response.graded and response.score == points %}
              {% if points == 0 %}
              class="btn btn-sm btn-danger"
              {% else %}
              class="btn btn-sm btn-success"
              {% endif %}
            disabled
            {% else %}
            class="btn btn-sm btn-outline-primary"
            {% endif %}
            hx-post="{% url 'assign_score' game.id %}"
            hx-vals='{"response":{{ response.id }},"score":{{points}} }'
            hx-target="#question-card-{{ response.question.id }}"
            hx-swap="outerHTML"><span class="px-1">{{ points }}</span></button>
          {% if not forloop.last %}
          {% cycle '' '' '' '' '</div><br><div class="btn-group mt-1" role="group">' %}
          {% endif %}
          {% endfor %}
          {% resetcycle %}
          </div>
      </td>
      <td>{% if not response.graded %}⚠️ {% endif %}{{ response.value }}</td>
      <td><abbr title="{{ response.team.members }}">{{ response.team.name }}</abbr></td>
    </tr>
    {% endfor %}
    </table>
  </div>
</div>

host/templates/host/_team_form.html
<form hx-target="this" hx-swap="outerHTML" hx-put="{{ put_url }}">
  <p>Team name: {{ form.name }}</p>
  <p>Members: {{ form.members }}</p>
  <p>
    <button class="btn btn-primary">Update info</button>
    <button class="btn btn-outline-secondary" hx-get="{{ get_url }}">Cancel</button>
  </p>
</form>

host/templates/host/_team_fragment.html
<div hx-target="this" hx-swap="outerHTML">
  <h2><em>{{ team.name }}</em></h2>
  <p>Members: {{ team.members }}</p>
  <p>
    <button
      class="btn btn-outline-primary"
      hx-get="{% url 'edit_team' game.id team.id %}">Edit team</button>
  </p>
</div>

host/templates/host/_update_game_state.html
{% load guardian_tags %}
{% get_obj_perms user for game as "perms" %}
<p>
  Game state: {{ game.get_state_display|lower }}<br>
  {% if 'host_game' in perms %}
  <button class="btn btn-sm btn-outline-danger"
    {% if game.is_closed %}disabled{% endif %}
    hx-post="{% url 'update_game_state' game.id 0 %}"
    hx-swap="outerHTML"
    hx-target="closest p">{% if game.is_closed %}Game is closed{%else%}Close game{% endif %}</button>
  <button class="btn btn-sm btn-{% if game.is_accepting_teams %}outline-{% endif %}primary"
    {% if game.is_accepting_teams %}disabled{% endif %}
    hx-post="{% url 'update_game_state' game.id 1 %}"
    hx-swap="outerHTML"
    hx-target="closest p">{% if game.is_accepting_teams %}New teams are allowed{%else%}Allow new teams{% endif %}</button>
  <button class="btn btn-sm btn-{% if game.is_open_but_not_accepting_teams %}outline-{% endif %}primary"
    {% if game.is_open_but_not_accepting_teams %}disabled{% endif %}
    hx-post="{% url 'update_game_state' game.id 2 %}"
    hx-swap="outerHTML"
    hx-target="closest p">{% if game.is_open_but_not_accepting_teams %}New teams are blocked{%else%}Block new teams{% endif %}</button>
  {% endif %}
</p>

host/templates/host/home.html
{% extends 'host_base.html' %}
{% block heading %}Tr¿via hosting{% endblock %}
{% block contents %}
<div class="row">
  <div class="col-12">
    <p><span class="badge bg-warning">Reminder</span> If any player is having browser trouble, give them this link: <code>{{ uncurse_url }}</code></p>
    <p>You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <hr>
    <h2>Games</h2>
    <p><a href="{% url 'new_game' %}" class="btn btn-outline-secondary{% if not perms.game.add_game %} disabled{% endif %}">Create a new game</a></p>
    <div>
    {% include 'host/_games_list.html' %}
    </div>
    <h2>Notes for hosts</h2>
    <p>
      The game tries to keep things stable and understandable for the players.
      The interface can be a little inscrutable for the host, though.
      This documentation should be helpful in understanding what's what.
    </p>
    <h3>Game states</h3>
    <p>
      A <b>game</b> can be closed or open.
    </p>
    <ul>
      <li>
        Closed - no players can join or see anything.
        As a host, you may use the editor interface.
      </li>
      <li>
        Open, allow new teams - players will be able to interact with the game.
        See below for how pages work within the game.
        As a host, the editor is disabled so that you can't accidentally break the game for players.
      </li>
      <li>
        Open, block new teams - existing teams have access, but no new teams can join.
      </li>
    </ul>
    </p>
    <h3>Page states</h3>
    <p>
      Games contain <b>pages</b>.
      Think of a page like a <q>round</q> in bar trivia.
      A page can be:
    </p>
    <ul>
      <li>Locked 🔒 - players may not interact at all, even the page title is hidden.</li>
      <li>Open ✏️ - players may answer and re-answer questions.</li>
      <li>Scoring ✋ - players may see what they answered, but may not change their answers. Scores will begin to become visible to players as you enter them.</li>
    </ul>
    <p>
      Additionally, pages have a flag called <q>hidden</q>.
      If a page is not hidden, then players will see its name as a series of question marks (<q>?????</q>) before it's open.
      If instead the page is marked hidden, it simply won't show up in the list until it's opened.
      In both cases, once the page is open, it will show up.
      This feature is intended to support hidden tie-breaker rounds.
      The idea is that players won't be confused by seeing a round which never opens, but you can have a tie-breaker ready to go in case it's needed.
    </p>

    <h3>Suggested flow</h3>
    <ol>
      <li>Open the game, blocking new teams if you prefer.</li>
      <li>Open the first page.</li>
      <li>When players are done or time is open, move the page to scoring.</li>
      <li>You can score immediately while players wait and show them the leaderboard, or you can announce and open the next round.</li>
      <li>At intervals (every round or two), show off the leaderboard. Pages should all be "locked" or "scoring", no page should be open while you do this.</li>
      <li>At the end, show off the final leaderboard.</li>
      <li>Close the game after everyone is done.</li>
    </ol>
  </div>
</div>
{% endblock %}

host/templates/host/pages.html
{% extends 'host_base.html' %}
{% block heading %}Host view: {{ game.name }}{% endblock %}
{% block contents %}
<div class="row justify-content-center">
  <div class="col-12 mb-2">
    <p>You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <h2>Game status</h2>
    <p>
      Visible points: {{ game_max_points }}<br>
      Hidden points: {{ game_hidden_points }}
    </p>
    {% include 'host/_update_game_state.html' %}
    <h2>Pages</h2>
    {# when the game or page state is toggled, this section reloads #}
    <div hx-get="{% url 'pages' game.id %}"
         hx-trigger="hostedGameStateUpdated from:body, pageStateUpdated from:body"
         name="pagesList">
    {% include 'host/_pages_list.html' %}
    </div>
  </div>
  <div class="col-12 mb-2">
    <h2>Teams ({{ game.team_set.count }})</h2>
    {% for team in game.team_set.all %}
    <p><a href="{% url 'team_page' game.id team.id %}"><em>{{ team.name }}</em></a>, which is: {% firstof team.members '<em>no players listed</em>' %}</p>
    {% empty %}
    <p>No teams have registered yet.</p>
    {% endfor %}
  </div>
  <div class="col-12 mb-2">
    <h2>Hosts</h2>
    <p>
    {% for host in game_hosts %}
    {% if host == request.user %}you{% else %}{% firstof host.get_full_name host %}{% endif %}{% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>
  </div>
  <div class="col-12 mb-2">
    <h2>Utilities</h2>
    <table class="table table-striped">
    <tr>
      <th>Player link</th><td><code>{{ player_join_url }}</code></td>
    </tr>
    <tr>
      <th>Leaderboard</th><td><a href="{% url 'host_leaderboard' game.id %}">Leaderboard</a></td>
    </tr>
    <tr>
      <th>Game data</th><td><a href="{% url 'game_data' game.id %}">Download JSON</a></td>
    </tr>
    <tr>
      <th>Host home</th><td><a href="{% url 'host_home' %}">Host home</a></td>
    </tr>
    </table>
  </div>
</div>
{% endblock %}