app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('backstage/', admin.site.urls),
    path('host/', include('host.urls')),
    path('', include('triviagame.urls')),
]

game/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('uncurse/', views.uncurse, name='uncurse'),
    path('join/', views.join_game, name='join_game'),
    path('join/<int:id>/<str:code>/', views.join_game, name='join_game'),
    path('join/team/', views.create_team, name='create_team'),
    path('rejoin/', views.rejoin_team, name='rejoin_team'),
    path('rejoin/<int:id>/<str:code>/', views.rejoin_team, name='rejoin_team'),
    path('play/', views.play, name='play'),
    path('play/p', views.page_list_hx, name='page_list_hx'),
    path('play/s', views.play_poll_hx, name='play_poll_hx'),
    path('play/<int:page_order>/', views.answer_sheet, name='answer_sheet'),
    path('play/q/<int:question_id>/', views.question_hx, name='question_hx'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('healthcheck/', views.healthcheck, name='healthcheck'),
]

host/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.host_home, name='host_home'),
    path('<int:game_id>/toggle/<int:new_state>', views.update_game_state, name='update_game_state'),
    path('<int:game_id>/pages/', views.pages, name='pages'),
    path('<int:game_id>/pages/state/', views.set_page_state, name='set_page_state'),
    path('<int:game_id>/pages/<int:page_id>', views.score_page, name='score_page'),
    path('<int:game_id>/score/', views.assign_score, name='assign_score'),
    path('<int:game_id>/game.json', views.game_data, name='game_data'),
    path('<int:game_id>/leaderboard.json', views.host_leaderboard_stats, name='host_leaderboard_stats'),
    path('<int:game_id>/leaderboard', views.host_leaderboard, name='host_leaderboard'),
    path('<int:game_id>/team/<int:team_id>', views.team_page, name='team_page'),
    path('<int:game_id>/team/<int:team_id>/edit', views.hx_edit_team, name='edit_team'),
    path('editor/new/', views.new_game, name='new_game'),
    path('editor/<int:game_id>/', views.edit_game, name='edit_game'),
    path('editor/<int:game_id>/audit', views.audit_game, name='audit_game'),
    path('editor/<int:game_id>/hosts', views.edit_game_hosts, name='edit_game_hosts'),
    path('editor/<int:game_id>/hosts/<int:user_id>', views.hx_remove_game_host, name='remove_game_host'),
    path('editor/page/<int:page_id>/', views.edit_page, name='edit_page'),
    path('editor/page/<int:page_id>/metadata/', views.hx_edit_page_metadata, name='edit_page_metadata'),
    path('editor/page/<int:page_id>/up/', views.page_move, { 'delta': -1 }, name='page_up'),
    path('editor/page/<int:page_id>/down/', views.page_move, { 'delta': 1 }, name='page_down'),
    path('editor/page/new/<int:game_id>/', views.new_page, name='new_page'),
    path('editor/page/<int:page_id>/delete/', views.delete_page, name='delete_page'),
    path('editor/question/<int:question_id>/', views.edit_question, name='edit_question'),
    path('editor/question/<int:question_id>/up/', views.question_move, { 'delta': -1 }, name='question_up'),
    path('editor/question/<int:question_id>/down/', views.question_move, { 'delta': 1 }, name='question_down'),
    path('editor/question/new/<int:page_id>/', views.new_question, name='new_question'),
    path('editor/question/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('auth/prelogout', views.host_confirm_logout, name='confirm_logout'),
    path('auth/', include('django.contrib.auth.urls')),
]

triviagame/urls.py
from django.contrib import admin
from django.urls import path, include

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('backstage/', admin.site.urls),
    path('host/', include('host.urls')),
    path('', include('game.urls')),
] + debug_toolbar_urls()

app/host/models.py
from django.contrib.auth import get_user_model
from django.db import models

from triviagame.models import Game


class GameHostPermissions(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    can_view = models.BooleanField()
    can_host = models.BooleanField()
    can_edit = models.BooleanField()

    def __str__(self):
        perm_bits = "".join([
            "E" if self.can_edit else "-",
            "H" if self.can_host else "-",
            "V" if self.can_view else "-",
        ])
        return f"{self.user}@{self.game}: {perm_bits}"

game/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.crypto import get_random_string


def generate_passcode():
    return get_random_string(10, 'ABCDEFGHJKLMNPQRTUVWXYZ2346789')


class Game(models.Model):
    class GameState(models.IntegerChoices):
        CLOSED = 0          # game can't be accessed
        ACCEPTING_TEAMS = 1 # game is open, new teams can register
        NO_NEW_TEAMS = 2    # game is open, only existing teams can access

    name = models.CharField(max_length=60)
    passcode = models.CharField(max_length=20, default=generate_passcode)
    state = models.IntegerField(
        choices=GameState.choices,
        default=GameState.CLOSED,
    )
    last_edit_time = models.DateTimeField(
        auto_now=True,
        blank=True,
        editable=False,
    )

    class Meta:
        ordering = ['-last_edit_time']
        permissions = [
            ('host_game', 'Host game'),
        ]

    def __str__(self):
        return self.name
    
    @property
    def is_closed(self):
        return self.state == Game.GameState.CLOSED
    
    @property
    def is_accepting_teams(self):
        return self.state == Game.GameState.ACCEPTING_TEAMS

    @property
    def is_open_but_not_accepting_teams(self):
        return self.state == Game.GameState.NO_NEW_TEAMS

    @property
    def is_open(self):
        "Any kind of open, whether accepting new teams or not"
        return self.state != Game.GameState.CLOSED


class Team(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    members = models.CharField(max_length=200, blank=True)
    passcode = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['game', 'name']
        constraints = [
            models.UniqueConstraint(
                fields=['game', 'name'],
                name='ensure_unique_team_names',
            ),
        ]


class Page(models.Model):
    MYSTERIES = [
        'The mysterious future...',
        'All will be revealed in time.',
        'Wouldn\'t you like to know?',
        'The suspense must be killing you!',
        'It\'s a secret to everybody.',
    ]

    class PageState(models.IntegerChoices):
        LOCKED = 0      # players cannot open the page at all
        OPEN = 1        # players can open and answer the page
        SCORING = 2     # players can open, but not answer, the page

    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    order = models.SmallIntegerField()
    state = models.IntegerField(
        choices=PageState.choices,
        default=PageState.LOCKED,
    )
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    is_hidden = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.game} :: {self.order}. {self.title}"
    
    class Meta:
        ordering = ['game', 'order']
        constraints = [
            models.UniqueConstraint(
                fields=['game', 'order'],
                name='ensure_page_order',
            ),
        ]
    
    def mystery_description(self):
        index = self.game.id + self.order
        return Page.MYSTERIES[index % len(Page.MYSTERIES)]

    # these properties are convenient in templates    
    @property
    def total_points(self):
        return (
            self.question_set
            .aggregate(points=models.Sum('possible_points'))
        ).get('points', None) or 0

    @property
    def is_locked(self):
        return self.state == Page.PageState.LOCKED
    
    @property
    def is_open(self):
        return self.state == Page.PageState.OPEN
    
    @property
    def is_scoring(self):
        return self.state == Page.PageState.SCORING
    
    @property
    def bootstrap_locked_button_styles(self):
        match self.state:
            case Page.PageState.LOCKED:
                return 'btn-outline-secondary disabled'
            case Page.PageState.OPEN:
                return 'btn-outline-primary'
            case Page.PageState.SCORING:
                return 'btn-outline-primary'
        return ''
    
    @property
    def bootstrap_open_button_styles(self):
        match self.state:
            case Page.PageState.LOCKED:
                return 'btn-primary'
            case Page.PageState.OPEN:
                return 'btn-outline-secondary disabled'
            case Page.PageState.SCORING:
                return 'btn-outline-primary'
        return ''
    
    @property
    def bootstrap_scoring_button_styles(self):
        match self.state:
            case Page.PageState.LOCKED:
                return 'btn-outline-primary'
            case Page.PageState.OPEN:
                return 'btn-primary'
            case Page.PageState.SCORING:
                return 'btn-outline-secondary disabled'
        return ''
    # end template properties


class Question(models.Model):
    page = models.ForeignKey(Page, on_delete=models.PROTECT)
    order = models.SmallIntegerField()
    question = models.TextField()
    answer = models.TextField(blank=True)
    possible_points = models.SmallIntegerField(
        default=1,
        validators=[MinValueValidator(limit_value=1)],
    )

    def __str__(self):
        return f"{self.order}. {self.question}"

    class Meta:
        ordering = ['page', 'order']
        constraints = [
            models.UniqueConstraint(
                fields=['page', 'order'],
                name='ensure_question_order',
            ),
        ]
    
    def points_range(self):
        return range(0, self.possible_points + 1)


class Response(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    value = models.CharField(max_length=100)
    graded = models.BooleanField(default=False)
    score = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.value

    class Meta:
        ordering = ['question', 'team']
        constraints = [
            models.UniqueConstraint(
                fields=['question', 'team'],
                name='one_answer_per_team',
            ),
        ]

host/models.py
from django.db import models

app/host/forms.py
from django import forms
from triviagame.models import Game, Page, Question
from triviagame.widgets import Bs5TextInput, Bs5Textarea



class SomePageForm(forms.Form):
    page = forms.IntegerField(widget=forms.HiddenInput)


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'name',
        ]
        widgets = {
            'name': Bs5TextInput,
        }
        labels = {
            'name': 'Game name',
        }


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = [
            'title',
            'description',
        ]
        widgets = {
            'title': Bs5TextInput,
            'description': Bs5Textarea,
        }
        labels = {
            'title': 'Page title',
            'description': 'Long description',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'question',
            'answer',
        ]
        widgets = {
            'question': Bs5Textarea,
            'answer': Bs5Textarea,
        }

game/forms.py
from django import forms

from .models import Team
from .widgets import Bs5TextInput, Bs5NumberInput


class JoinGameForm(forms.Form):
    id = forms.IntegerField(label="Game ID", widget=Bs5NumberInput)
    code = forms.CharField(label="Code", max_length=20, widget=Bs5TextInput)


class CreateTeamForm(forms.ModelForm):
    TEAM_NAME_IDEAS = (
        # "Win, Booze, or Draw",
        "Red Hot Trivia Peppers",
        # "The Smartinis",
        # "The Scranton Stranglers",
        "Harry, You're a Quizard",
        "I Can't Feel My Mace When I'm Windu",
        "Jar Jar Thinks",
        "Walt Quizney World",
        "Bears, Beets, Battlestar Galactica",
        "Dame Agatha Quiztie",
        "Alternative Facts",
        "Air of Truthiness",
        "Les Quizerables",
        "John Trivialta",
        "Risky Quizness",
        "Trivia Newton John",
        "Quizteama Aguilera",
        "Just Google It",
        "Walt Quizney",
        "Quiz Pro Quo",
        "The Quizard of Oz",
        "Don Quizote",
        "Get Down to Quizness",
        "Quizly Bears",
        "Misery Quizness",
    )

    class Meta:
        model = Team
        fields = ('name', 'members')
        widgets = {
            'name': Bs5TextInput(attrs={
                'data-1p-ignore': True,
                'autocomplete': 'off',
            }),
            'members': Bs5TextInput(
                attrs={
                    'autocomplete': 'off',
                }
            ),
        }
        labels = {
            'name': 'Team name',
            'members': 'Team members (for display only, separate with spaces, commas, or whatever you want)',
        }


class ReJoinTeamForm(forms.Form):
    id = forms.IntegerField(label="Team ID", widget=Bs5NumberInput)
    code = forms.CharField(label="Code", max_length=20, widget=Bs5TextInput)

host/forms.py
from django import forms
from django.contrib.auth import get_user_model

from game.models import Game, Page, Question, Team
from game.widgets import (
    Bs5TextInput,
    Bs5NumberInput,
    Bs5Textarea,
    Bs5Select,
)


User = get_user_model()


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'name',
        ]
        widgets = {
            'name': Bs5TextInput(attrs={
                'data-1p-ignore': True,
                'autocomplete': 'off',
            }),
        }
        labels = {
            'name': 'Game name',
        }


class GameHostForm(forms.Form):
    host = forms.ModelChoiceField(
        None,
        required=True,
        label="Add additional host",
        widget=Bs5Select,
    )

    def __init__(self, data=None, queryset=None, *args, **kwargs):
        super().__init__(data, *args, **kwargs)
        self.fields['host'].queryset = queryset


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = [
            'title',
            'description',
            'is_hidden',
        ]
        widgets = {
            'title': Bs5TextInput(attrs={
                'autocomplete': 'off',
            }),
            'description': Bs5Textarea,
        }
        labels = {
            'title': 'Page title',
            'description': 'Long description (Markdown allowed)',
            'is_hidden': 'Hide this page while it\'s not open?',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'question',
            'answer',
            'possible_points',
        ]
        widgets = {
            'question': Bs5Textarea,
            'answer': Bs5Textarea,
            'possible_points': Bs5NumberInput,
        }
        labels = {
            'question': 'Question (Markdown allowed)',
            'answer': 'Answer (Markdown allowed)',
        }


class TeamForm(forms.Form):
    name = forms.CharField(
        label='Team name',
        max_length=200,
        widget=Bs5TextInput(attrs={
            'autocomplete': 'off',
            'data-1p-ignore': True,
        }),
    )
    members = forms.CharField(
        label='Team members (display only, no required format)',
        max_length=200,
        required=False,
        widget=Bs5TextInput(attrs={
            'autocomplete': 'off',
        }),
    )

host/templates/editor/_page_form.html
<form method="post" autocomplete="off"
  hx-post="{% url 'edit_page_metadata' page.id %}"
  hx-target="closest div">
  {% csrf_token %}
  {{ page_form }}
  <button type="submit" class="btn btn-outline-primary mt-3">Save page metadata</button>
</form>

host/templates/editor/_page_list.html
<tbody id="page-list">
{% for page in game.page_set.all %}
<tr>
  <td>{{ page.order }}. {% if page.is_hidden %}<i>{% endif %}<a href="{% url 'edit_page' page.id %}">{{ page.title }}</a>{% if page.is_hidden %}</i> (hidden 🙈){% endif %}</td>
  <td>{{ page.total_points }} point{{ page.total_points|pluralize }}</td>
  <td><a hx-post="{% url 'page_up' page.id %}" hx-target="#page-list" hx-swap="outerHTML" class="btn btn-outline-success{% if forloop.first %} disabled{% endif %}">Move up 👆</a></td>
  <td><a hx-post="{% url 'page_down' page.id %}" hx-target="#page-list" hx-swap="outerHTML" class="btn btn-outline-success{% if forloop.last %} disabled{% endif %}">Move down 👇</a></td>
  <td><a href="{% url 'delete_page' page.id %}" class="btn btn-outline-danger">Delete</a></td>
</tr>
{% empty %}
<tr><td class="list-group-item text-secondary">No pages yet</td></tr>
{% endfor %}
</tbody>

host/templates/editor/_question_list.html
<div id="question-list">
{% for question in page.question_set.all %}
<div class="card mb-3">
  <div class="card-header">Question {{ question.order }}</div>
  <div class="card-body">
    {% if question.possible_points > 1 %}<p class="card-text fst-italic">Worth up to <span class="text-primary fw-bold">{{ question.possible_points }}</span> points.</p>{% endif %}
    <p class="card-text markdown-needed">{{ question.question }}</p>
    <div class="hstack gap-2 mb-3 p-1 border rounded-start bg-secondary-subtle">
      <div class="">Answer</div>
      <div class="vr"></div>
      <div class="markdown-needed">{{ question.answer }}</div>
    </div>
    <a href="{% url 'edit_question' question.id %}" class="btn btn-outline-primary">Edit</a>
    <a hx-post="{% url 'question_up' question.id %}" hx-target="#question-list" class="btn btn-outline-success{% if forloop.first %} disabled{% endif %}">Move up 👆</a>
    <a hx-post="{% url 'question_down' question.id %}" hx-target="#question-list" class="btn btn-outline-success{% if forloop.last %} disabled{% endif %}">Move down 👇</a>
    <a href="{% url 'delete_question' question.id %}" class="btn btn-outline-danger">Delete</a>
  </div>
</div>
{% endfor %}
</div>

host/templates/editor/audit.html
{% extends 'host_base.html' %}
{% block title %}👑 Tr¿via editor{% endblock %}
{% block heading %}<q>{{ game.name }}</q> audit{% endblock %}
{% block contents %}
<div class="row justify-content-center">
  <div class="col-12">
    <p class="d-print-none">You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <div class="card mb-3">
      <div class="card-header bg-primary text-white">Game metadata</div>
      <div class="card-body">
        <h4>Name: {{ game.name }}</h4>
        <p class="card-text mt-2">
          Hosts:
          {% for host in game_hosts %}
          {% if host == request.user %}you{% else %}{% firstof host.get_full_name host %}{% endif %}{% if not forloop.last %}, {% endif %}
          {% endfor %}<br>
          Pages: {{ game.page_set.count }}<br>
          Nomal points: {{ game_max_points }}<br>
          Hidden points: {{ game_hidden_points }}
        </p>
      </div>
    </div>

    {% for page in game.page_set.all %}
    <div class="card mb-3">
      <div class="card-header">
        {{ page.order }}. {{ page.title }}{% if page.is_hidden %} (hidden){% endif %}
      </div>
      <div class="card-body markdown-needed">{{ page.description }}</div>
      <div class="card-body d-print-none"><small><a href="{% url 'edit_page' page.id %}" target="_blank">[edit page]</a></small></div>
      <div class="card-body">
        <table class="table table-striped">
          <tr><th>#</th><th>Points</th><th>Question</th><th>Answer</th><th class="d-print-none">Edit</th></tr>
          {% for question in page.question_set.all %}
          <tr>
            <td>{{ question.order }}</td>
            <td>{{ question.possible_points }}</td>
            <td class="markdown-needed">{{ question.question }}</td>
            <td class="markdown-needed">{{ question.answer }}</td>
            <td class="d-print-none"><a href="{% url 'edit_question' question.id %}" target="_blank">[edit]</a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="card-footer">
        Total points: {{ page.total_points }}
      </div>
    </div>
    {% endfor %}

    <div class="col-12 mb-2 d-print-none">
      <h2>Utilities</h2>
      <table class="table table-striped">
      <tr>
        <th>Editor home</th><td><a href="{% url 'edit_game' game.id %}">Edit this game</a></td>
      </tr>
      <tr>
        <th>Host home</th><td><a href="{% url 'host_home' %}">Return to host interface</a></td>
      </tr>
      </table>
    </div>
  </div>
</div>
{% endblock %}

host/templates/editor/delete_page.html
{% extends 'host_base.html' %}
{% block title %}👑 Tr¿via editor{% endblock %}
{% block heading %}Really delete page <q>{{ page.title }}</q>?{% endblock %}
{% block contents %}
<div class="row justify-content-center">
  <div class="col-12">
    <p>You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <div class="card mb-3">
      <div class="card-header bg-danger text-white">Deleting page <q><a href="{% url 'edit_page' page.id %}" class="link-light">{{ page.title }}</a></q> in game <q><a href="{% url 'edit_game' page.game.id %}" class="link-light">{{ page.game.name }}</a></q></div>
      <div class="card-body">
          <h5 class="card-title">{{ page.order }}. {{ page.title }}</h5>
          <p class="card-text markdown-needed">{{ page.description }}</p>
          {% if page.question_set.count %}
          <p><em>This will delete {{ page.question_set.count }} questions!!</em></p>
          {% endif %}
          <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">Yes, delete the page</button>
            <a href="{% url 'edit_game' page.game.id %}" class="btn btn-outline-secondary">Nope, changed my mind</a>
        </form>    
      </div>
    </div>
  </div>
</div>
{% endblock %}

host/templates/editor/delete_question.html
{% extends 'host_base.html' %}
{% block title %}👑 Tr¿via editor{% endblock %}
{% block heading %}Really delete question {{ question.order }} from page {{ question.page.order }}?{% endblock %}
{% block contents %}
<div class="row justify-content-center">
  <div class="col-12">
    <p>You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <div class="card mb-3">
      <div class="card-header bg-danger text-white">Deleting question {{ question.order }} from page <q><a href="{% url 'edit_page' question.page.id %}" class="link-light">{{ question.page.title }}</a></q> in game <q><a href="{% url 'edit_game' question.page.game.id %}" class="link-light">{{ question.page.game.name }}</a></q></div>
      <div class="card-body">
          <div class="hstack gap-2 mb-3 p-1">
            <div class="">Question</div>
            <div class="vr"></div>
            <div class="markdown-needed">{{ question.question }}</div>
          </div>

          <div class="hstack gap-2 mb-3 p-1 border rounded-start bg-secondary-subtle">
            <div class="">Answer</div>
            <div class="vr"></div>
            <div class="markdown-needed">{{ question.answer }}</div>
          </div>
          <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">Yes, delete the question</button>
            <a href="{% url 'edit_page' question.page.id %}" class="btn btn-outline-secondary">Nope, changed my mind</a>
        </form>    
      </div>
    </div>
  </div>
</div>
{% endblock %}

host/templates/editor/hosts.html
{% extends 'host_base.html' %}
{% block title %}👑 Tr¿via editor{% endblock %}
{% block heading %}Editing hosts for <q>{{ game.name }}</q>{% endblock %}
{% block contents %}
<div class="row justify-content-center">
  <div class="col-12">
    <p>You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <div class="card mb-3">
      <div class="card-header bg-primary text-white">Edit hosts</div>
      <div class="card-body">
        <p class="card-text">Game: {{ game.name }}</p>

        <p class="card-text">Hosts (you can't remove admins or yourself):</p>
        <ul class="list-group list-group-flush">
          {% for host in game_hosts %}
          {% if host == request.user %}
          <li class="list-group-item">
            {% firstof host.get_full_name host %}
            <span class="badge rounded-pill bg-primary">you</span>
          </li>
          {% elif host.is_superuser %}
          <li class="list-group-item">
            {% firstof host.get_full_name host %}
            <span class="badge rounded-pill bg-secondary">admin</span>
          </li>
          {% else %}
          <li class="list-group-item" id="host-{{ host.id }}">
            {% firstof host.get_full_name host %}
            <button class="btn btn-danger btn-sm ms-2"
              hx-delete="{% url 'remove_game_host' game.id host.id %}"
              hx-target="#host-{{ host.id }}"
              >Remove host</button>
          </li>
          {% endif %}
          {% endfor %}
        </ul>

        {% if any_hosts_to_add %}
        <form method="post" autocomplete="off">
          <p class="card-text">
            {% csrf_token %}
            {{ game_host_form }}
          </p>
          <button type="submit" class="btn btn-outline-primary">Add host</button>
        </form>
        {% else %}
        <p class="card-text mt-3 fst-italic">Everyone who could be a host of this game is already a host!</p>
        {% endif %}

      </div>
    </div>

    <a href="{% url 'edit_game' game.id %}">Return to game editor</a>
  </div>
</div>
{% endblock %}

host/templates/editor/page.html
{% extends 'host_base.html' %}
{% block title %}👑 Tr¿via editor{% endblock %}
{% block heading %}Editing page <q>{{ page.title }}</q>{% endblock %}
{% block contents %}
<div class="row justify-content-center">
  <div class="col-12">
    <p>You are logged in as <span class="text-success">{% firstof request.user.get_full_name request.user %}</span>{% if request.user.is_superuser %} <span class="badge rounded-pill bg-secondary">admin</span>{% endif %} (<a class="link-danger" href="{% url 'confirm_logout' %}">log out</a>)</p>
    <p>Go back to game editor: <q><a href="{% url 'edit_game' page.game.id %}">{{ page.game.name }}</a></q></p>
    <div class="card mb-3">
      <div class="card-header bg-primary text-white">Page metadata</div>
      <div class="card-body">
        <form>
          <div>
            <label for="id_title">Page title:</label>
            <div class="mb-3">
              <input type="text" readonly class="form-control-plaintext" id="id_title" value="{{ page.title }}">
            </div>
          </div>

          <div>
            <label for="id_desc">Long description:</label>
            <div class="mb-3">
              <div class="form-control mt-1 markdown-needed" id="id_desc">{{ page.description }}</div>
            </div>
          </div>

          <div>
            <label class="mb-3">Hidden: {% if page.is_hidden %}Yes{% else %}No{% endif %}</label>
          </div>
        </form>

        <p class="card-text">
          <a class="btn btn-outline-primary"
            hx-get="{% url 'edit_page_metadata' page.id %}"
            hx-target="closest div">Edit page metadata</a>
        </p>
      </div>
    </div>

    {% if page.question_set.count > 0 %}
    <p><a href="{% url 'new_question' page.id %}" class="btn btn-primary">Add new question (at bottom)</a></p>
    {% endif %}

    {% include 'editor/_question_list.html' %}

    <p><a href="{% url 'new_question' page.id %}" class="btn btn-primary">Add new question</a></p>

  </div>
</div>
{% endblock %}